project:
  type: website
  output-dir: docs

website:
  title: "Bayes14"
  navbar:
    left:
      - posts.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      light: flatly
      dark: solar
    css: styles.css



