project:
  type: website
  output-dir: docs

website:
  title: "Bayes14"
  navbar:
    left:
      - posts.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  page-footer:
    center: "Copyright 2023, Mads Chr. Hansen"
  repo-url: https://github.com/bayes14/bayes14.github.io
  repo-actions: [source]
format:
  html:
    theme:
      light: flatly
      dark: solar
    css: styles.css



